join_light/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
    path('social/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from .views import index, by_category, book_detail_view
from django.conf import settings
from django.conf.urls.static import static
from .views import other_page

from django.urls import reverse_lazy



#

from .views import JobLoginView
from .views import profile
from .views import JobLogoutView
from .views import ChangeUserInfoView
from .views import JobPasswordChangeView
from .views import RegisterUserView, RegisterDoneView
from .views import user_activate
from .views import DeleteUserView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView


app_name = 'main'
urlpatterns = [
    path('<int:category_id>/', by_category, name="by_category"),
    path('vacancy/<int:vacancy_id>/', book_detail_view, name="vacancy"),
    path('', index, name='index'),
    path('contact/', views.contactform, name='contact'),
    path('contact/thanks/', views.thanks, name='thanks'),
    path('<str:page>/', other_page, name='other') ,

    path('accounts/login/', JobLoginView.as_view(), name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', JobLogoutView.as_view(), name='logout'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('acoounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', JobPasswordChangeView.as_view(), name='password_change'),
    path('acoounts/register/done/', RegisterDoneView.as_view(), name="register_done"),
    path('acoounts/register/', RegisterUserView.as_view(), name="register"),
    path('acoounts/register/activate/<str:sign>/', user_activate, name='register_activate'),

    path('accounts/password_reset', PasswordResetView.as_view(template_name="registration/reset_password.html",
                                                              subject_template_name='email/reset_subject.txt',
                                                              email_template_name='email/reset_email.html',
                                                              success_url=reverse_lazy('main:password_reset_done')),
         name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(template_name='registration/email_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/confirm_password.html', success_url=reverse_lazy(
             'main:password_reset_complete')), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_confirmed.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

from django.dispatch import Signal

from .utilities import send_activation_notification
# Create your models here.

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
    verbose_name='Is active?')
    send_messages = models.BooleanField(default=True,
    verbose_name='Send alerts?')
    class Meta(AbstractUser.Meta):
        pass


user_registrated = Signal(providing_args=['instance'])

def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])

user_registrated.connect(user_registrated_dispatcher)



# Create your models here.
class Сategory(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name='Name')
    img = models.FileField(upload_to='img', null=True, blank=True, verbose_name='Сategory_img'
                            )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Сategory'
        ordering = ['name']


class Subcategory(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name='Name')
    img = models.FileField(upload_to='img', null=True, blank=True, verbose_name='Subcategory_img')



    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Subcategories'
        verbose_name = 'Subcategory'
        ordering = ['name']

class Employment_type(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name='Name')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Employments'
        verbose_name = 'Employment'
        ordering = ['name']


class Skill(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name='Name')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'
        ordering = ['name']


class Vacancie(models.Model):
    title = models.CharField(max_length=50, verbose_name='Title')
    description = models.TextField(null=True, blank=True, verbose_name='Description')
    category = models.ForeignKey('Сategory', null=True, on_delete=models.PROTECT, verbose_name='Сategory')
    subcategores = models.ManyToManyField('Subcategory', verbose_name='Subcategory')
    employment = models.ForeignKey('Employment_type', null=True, on_delete=models.PROTECT, verbose_name='Employmet type')
    skill = models.ForeignKey('Skill', null=True, blank=True, on_delete=models.PROTECT,
                                   verbose_name='Skill')
    img = models.ImageField(upload_to='img', null=True, blank=True, verbose_name='Vacancy_img'
                            )
    email = models.EmailField(max_length=50, null=True, blank=True, verbose_name='Email')
    location = models.TextField(null=True, blank=True, verbose_name='Location')
    salary = models.FloatField(null=True, blank=True)
    company = models.CharField(max_length=70, null=True, blank=True,verbose_name='Company')
    url = models.CharField(max_length=50, null=True, blank=True, verbose_name='Url')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')
    requirements = models.TextField(null=True, blank=True, verbose_name='requirements')
    tasks = models.TextField(null=True, blank=True, verbose_name='Tasks')
    terms = models.TextField(null=True, blank=True, verbose_name='Terms')
    telegram = models.CharField(max_length=50, null=True, blank=True, verbose_name='Telegram')


    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Vacancies'
        verbose_name = 'Vacancy'
        ordering = ['-published']

main/forms.py
from django import forms

##
from . import models
from .models import AdvUser


from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import user_registrated






# Модель формы обратной связи
class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='E-mail')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


#Регистрация
class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='E-mail')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput, help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Password repeat', widget=forms.PasswordInput, help_text='Enter password for verification')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')

main/views.py
from django.contrib import auth
from django.core.mail import send_mail
from django.shortcuts import render

from . import forms
from .models import Vacancie, Сategory, Subcategory
from django.http import HttpResponse, Http404, BadHeaderError, HttpResponseRedirect, request
from django.template import TemplateDoesNotExist
from .forms import ContactForm
from django.template.loader import get_template


from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

####
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.edit import UpdateView, FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404

from django.views.generic.edit import CreateView

from .models import AdvUser
from .forms import ChangeUserInfoForm

from django.contrib.auth.views import PasswordChangeView

from .forms import RegisterUserForm
from django.views.generic.base import TemplateView


from django.core.signing import BadSignature
from .utilities import signer


from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages

from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend





#Прочие страницы
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

# Create your views here.
def index(request):
    vacancies = Vacancie.objects.all()
    categories = Сategory.objects.all()
    count_vacancies = Vacancie.objects.all().count()
    context = {'vacancies': vacancies, 'categories':categories, 'count_vacancies':count_vacancies}
    return render(request, 'main/index.html', context)

def by_category(request, category_id):
    vacancies = Vacancie.objects.filter(category=category_id)
    categories = Сategory.objects.all()
    count_vacancies = Vacancie.objects.filter(category=category_id).count()
    current_category = Сategory.objects.get(pk=category_id)
    context = {'vacancies': vacancies, 'categories': categories, 'current_category':current_category,'count_vacancies':count_vacancies}
    return render(request, 'main/by_category.html', context)


def book_detail_view(request, vacancy_id):
    try:
        vacancy = Vacancie.objects.get(pk=vacancy_id)
        categories = Сategory.objects.all()
    except Vacancie.DoesNotExist:
        raise Http404("Vacancy does not exist")

    return render(
        request,
        'main/vacancy_detail.html',
        context={'vacancy': vacancy, 'categories': categories,}
    )

# Функция формы обратной связи
def contactform(reguest):
    if reguest.method == 'POST':
        form = ContactForm(reguest.POST)
        # Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recepients = ['sizze.team@gmail.com']
            # Если пользователь захотел получить копию себе, добавляем его в список получателей
            if copy:
                recepients.append(sender)
            try:
                send_mail(subject, message, 'sizze.team@gmail.com', recepients)
            except BadHeaderError: #Защита от уязвимости
                return HttpResponse('Invalid header found')
            # Переходим на другую страницу, если сообщение отправлено
            return HttpResponseRedirect('thanks')

    else:
        form = ContactForm()
    # Выводим форму в шаблон
    return render(reguest, 'forms/contact.html', {'form': form, 'username': auth.get_user(reguest).username})

def thanks(reguest):
    thanks = 'thanks'
    return render(reguest, 'forms/thanks.html', {'thanks': thanks})

#######
#Профиль вход
class JobLoginView(LoginView):
    template_name = 'registration/login.html'


@login_required
def profile(request):
    return render(request, 'registration/profile.html')

#Профиль выход
class JobLogoutView(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy('main:index')
  # template_name = 'registration/logout.html'
    success_url = 'main:index'

#Редактирование профиля
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView) :
    model = AdvUser
    template_name = 'registration/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile_change')
    success_message = "Changed"

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)
#Смена пароля
class JobPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'registration/password_changed.html'
    success_url = reverse_lazy('main:password_change')
    success_message = 'password changed'

#Регистрация
class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'registration/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')

class RegisterDoneView(TemplateView):
    template_name = 'registration/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'registration/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'registration/user_is_activated.html'
    else:
        template = 'registration/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name='registration/delete_user.html'
    success_url = reverse_lazy('main:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS,
                           'User delated')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

main/templates/layout/basic.html
{% load static %}


<html data-wf-page="5f58872ddc5e51432f7fc846" data-wf-site="5f5201b9a6148561aa10e212">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Все вакансии{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Webflow" name="generator">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/webflow.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/joinio.webflow.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">
    <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
    <link href="{% static 'main/img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'main/img/webclip.png' %}" rel="apple-touch-icon">
</head>

<body data-w-id="5f5201b951c67f0c3b79e4b8" style="opacity:0" class="body">





    <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="navbar w-nav">
    <div class="w-container"><a href="{% url 'main:index' %}" aria-current="page" class="w-nav-brand w--current"><img src="{% static 'main/img/Logo-Join.svg'%}" loading="lazy" alt="" class="image-6"></a>
      <nav role="navigation" class="nav-menu w-nav-menu">
        <div data-hover="" data-delay="0" class="w-dropdown">
          <div data-w-id="37052b69-43e1-8b4c-9cdf-bb833def04d7" class="dropdown-toggle w-dropdown-toggle">
            <div class="w-icon-dropdown-toggle"></div>
            <div>Личный кабинет</div>
          </div>


            {% if user.is_authenticated %}

         <nav class="dropdown-list w-dropdown-list"><a href="{% url 'main:profile' %}" data-w-id="bdf4dbaa-eea3-2f90-9a02-c16597f23f0e" target="_self" class="dropdown-link-2 w-dropdown-link">Настройки</a><a href="{% url 'main:logout' %}" data-w-id="1005a791-d5a5-57df-b903-a5e6a361cab6" class="dropdown-link-3 w-dropdown-link">Выход</a></nav>
        {% else %}
                <nav class="dropdown-list w-dropdown-list"><a href="{% url 'main:register' %}" data-w-id="bdf4dbaa-eea3-2f90-9a02-c16597f23f0e" target="_self" class="dropdown-link-2 w-dropdown-link">Регистрация</a><a href="{% url 'main:login' %}" data-w-id="1005a791-d5a5-57df-b903-a5e6a361cab6" class="dropdown-link-3 w-dropdown-link">Вход</a></nav>
        {% endif %}

        </div><a href="{% url 'main:contact' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" class="nav-link-2 w-nav-link"">Опубликовать вакансию</a><a href="{% url 'main:index' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" class="nav-link-2 w-nav-link">Вакансии</a></nav>
      <div class="menu-button w-nav-button">
        <div class="icon w-icon-nav-menu"></div>
      </div>
    </div>
  </div>




{% block content %}
{% endblock %}

  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5f5201b9a6148561aa10e212" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="{% static 'main/js/webflow.js' %}" type="text/javascript"></script>
<script src="{% static 'main/js/main.js' %}" type="text/javascript"></script>
</body>
</html>

main/templates/layout/basic_registration.html
{% load bootstrap4 %}
{% load static %}


<html data-wf-page="5f58872ddc5e51432f7fc846" data-wf-site="5f5201b9a6148561aa10e212">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Все вакансии{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="Webflow" name="generator">
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/webflow.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/joinio.webflow.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">
    <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>
    <link href="{% static 'main/img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'main/img/webclip.png' %}" rel="apple-touch-icon">

</head>

<body data-w-id="5f5201b951c67f0c3b79e4b8" style="opacity:0" class="body">


  <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="navbar w-nav">
    <div class="w-container"><a href="{% url 'main:index' %}" aria-current="page" class="w-nav-brand w--current"><img src="{% static 'main/img/Logo-Join.svg'%}" loading="lazy" alt="" class="image-6"></a>
      {% if user.is_authenticated %}
          <nav role="navigation" class="nav-menu w-nav-menu"><a href="{% url 'main:contact' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535d" class="nav-link w-nav-link">Опубликовать вакансию</a><a href="{% url 'main:index' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" aria-current="page" class="nav-link-2 w-nav-link w--current">Вакансии</a><a href="{% url 'main:profile' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" aria-current="page" class="nav-link-2 w-nav-link w--current">Профиль</a><a href="{% url 'main:logout' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" aria-current="page" class="nav-link-2 w-nav-link w--current">Выход</a></nav>
        {% else %}
        <nav role="navigation" class="nav-menu w-nav-menu"><a href="{% url 'main:contact' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535d" class="nav-link w-nav-link">Опубликовать вакансию</a><a href="{% url 'main:index' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" aria-current="page" class="nav-link-2 w-nav-link w--current">Вакансии</a><a href="{% url 'main:register' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" aria-current="page" class="nav-link-2 w-nav-link w--current">Регистрация</a><a href="{% url 'main:login' %}" data-w-id="dbeecab7-b2d3-20bf-a356-f96fd39b535f" aria-current="page" class="nav-link-2 w-nav-link w--current">Вход</a></nav>
      {% endif %}
        <div class="menu-button w-nav-button">
        <div class="icon w-icon-nav-menu"></div>
      </div>
    </div>
  </div>


{% block content %}
{% endblock %}

  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5f5201b9a6148561aa10e212" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="{% static 'main/js/webflow.js' %}" type="text/javascript"></script>
<script src="{% static 'main/js/main.js' %}" type="text/javascript"></script>
</body>
</html>